#%RAML 1.0 NamedExample
values:
  -
    ID: 1
    amount: 50.00
    paymentdate: '2022-01-01'
    month: Ene
    comments: Pago de Enero
    
  -
    ID: 2
    amount: 50.00
    paymentdate: '2022-02-01'
    month: Feb
    comments: Pago de Febrero
  