#%RAML 1.0 NamedExample
value:
  -
    ID: 1
    name: partner_name
    phone: partner_phone
    status: true
  -
    ID: 2
    name: partner_name1
    phone: partner_phone1
    status: true
  -
    ID: 3
    name: partner_name3
    phone: partner_phone
    status: false